### ISSUE TITLE
Link to latest version on-chain

### ISSUE THREAD

**Issue by derekm** [shruggr/bottle-upload#1]
Latest version I know of is:

b://1a448b3c1b3a2a3de10fcb1293e60b81eea5c2c377d26d6c53f40b41522c2e04

https://bico.media/b://1a448b3c1b3a2a3de10fcb1293e60b81eea5c2c377d26d6c53f40b41522c2e04/

**Comment by RoyMurphy** [comment]
Thank you for sending me this link Derek.
I will certainly have a play in the sandpit.

**Comment by shruggr** [comment]
Created README.md with links
