### ISSUE TITLE
Upload process must survive broadcast endpoint timeout

### ISSUE THREAD

**Issue by derekm** [shruggr/bottle-upload#2]
If the broadcast endpoint times-out, the upload tool jumps straight to the end and erroneously displays the b:// and d:// URLs.

The upload process should reliably resume the upload wherever it left off using retries and possible user interaction.

**Comment by shruggr** [comment]
I have updated such that the broadcast queue is show to users, and the status will be updated in the case of an error, which will allow the user to rebroadcast any failed transactions.
