### ISSUE TITLE
Enable Upload button if Step 3 is done first

### ISSUE THREAD

**Issue by derekm** [shruggr/bottle-upload#4]
If Step 3 is done first, the Upload button remains disabled after split transactions are confirmed ready.

Refreshing to check if split transactions are confirmed ready should enable the Upload button if a file is already selected.

**Comment by Kakifrucht** [comment]
That was simple! You can test it [here](https://bico.media/B://390ca12e2990920b7c9ffe13f1ca8a0162c027f76716b380dbe38fc61b44315e)

**Comment by derekm** [comment]
Yeah, this one was the freebie!
